name: Compile FF files
on:
  pull_request:
    branches:
      - main
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.3
        with:
          diff_relative: true
          path: ff/source
      - name: Compile FF files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Compiling FF files..."
          echo "Changed files: ${ALL_CHANGED_FILES}"
          python scripts/compile_changes.py ${ALL_CHANGED_FILES}
          echo "Done compiling FF files"
      - name: Commit FF files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: "Compile FF files"
          add: "ff/files/*"
