name: Create release zip
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create zip file
        run: |
          zip MW2SpeedrunMod-part1.zip $(ls ff/files/* | head -10)
          zip MW2SpeedrunMod-part2.zip $(ls ff/files/* | tail -n +11)
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: MW2SpeedrunMod-part1.zip, MW2SpeedrunMod-part2.zip
          body: |
            This is the latest release of the MW2 Speedrun Mod.
            It contains the compiled FF files.

            Download the zip files and extract to your MW2/zones/{language} folder to install.
